config/routes.rb
Rails.application.routes.draw do

  resources :check_lists do
    resources :items do
    	member do
    		patch :complete
      end
    end
  end

  devise_for :users

  get 'home/index'

  root "home#index"
  # root "check_lists#index"
end

app/models/check_list.rb
# == Schema Information
#
# Table name: check_lists
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class CheckList < ActiveRecord::Base
	has_many :items
	belongs_to :user

	def create
	end
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id            :integer          not null, primary key
#  content       :string
#  check_list_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  completed     :boolean          default(FALSE)
#  user_id       :integer
#

class Item < ActiveRecord::Base
  belongs_to :check_list
  belongs_to :user

  def days_left
    7 - (DateTime.now.to_date - created_at.to_date).to_i
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :items
  has_many :check_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/check_lists_controller.rb
class CheckListsController < ApplicationController
  before_action :set_check_list, only: [:show, :edit, :update, :destroy]


  def index

    @check_lists = current_user.check_lists
  end

  def show
  end

  def new
    @check_list = CheckList.new
  end

  def edit
  end

  def create
    @check_list = current_user.check_lists.build(check_list_params)

    respond_to do |format|
      if @check_list.save
        format.html { redirect_to @check_list, notice: 'Check list was successfully created.' }
        format.json { render :show, status: :created, location: @check_list }
      else
        format.html { render :new }
        format.json { render json: @check_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @check_list.update(check_list_params)
        format.html { redirect_to @check_list, notice: 'Check list was successfully updated.' }
        format.json { render :show, status: :ok, location: @check_list }
      else
        format.html { render :edit }
        format.json { render json: @check_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @check_list.destroy
    respond_to do |format|
      format.html { redirect_to check_lists_url, notice: 'Check list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_check_list
    @check_list = CheckList.find(params[:id])
  end

  def check_list_params
    params.require(:check_list).permit(:title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	before_action :set_check_list
	before_action :set_item, except: [:create]

	def create
		@item = @check_list.items.create(item_params)
		@item.user = current_user
		redirect_to @check_list
	end

	def destroy
		@item = @check_list.items.find(params[:id])
		if @item.destroy
			flash[:success] = "Check List item was deleted successfully."
		else
			flash[:error] = "Check List item could not be deleted. Please try again."
		end
		redirect_to @check_list
	end

	def complete
		@item.update_attributes(completed: true)
		redirect_to @check_list, notice: "Item was completed."
	end



	private

	def set_check_list
		@check_list = CheckList.find(params[:check_list_id])
	end

	def set_item
		@item = @check_list.items.find(params[:id])
	end

	def item_params
		params[:item].permit(:content, :completed)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except:[:show]

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information was updated."
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Invalid user information."
      redirect_to edit_user_registration_path
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_lists_helper.rb
module CheckListsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/check_lists/_form.html.erb
<%= form_for(@check_list) do |f| %>
  <% if @check_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check_list.errors.count, "error") %> prohibited this check_list from being saved:</h2>

      <ul>
      <% @check_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/check_lists/edit.html.erb
<h1>Editing Check List</h1>

<%= render 'form' %>

<%= link_to 'Show', @check_list %> |
<%= link_to 'Back', check_lists_path %>

app/views/check_lists/index.html.erb
<% @check_lists.each do |check_list| %>
  <div class="index_row clearfix">
    <h2 class="check_list_title"><%= link_to check_list.title, check_list %></h2>
    <p class="check_list_sub_title"><%= check_list.description %></p>
  </div>
<% end %>
<div class="links">
  <%= link_to "New Check List", new_check_list_path %>
</div>

app/views/check_lists/new.html.erb
<h1>New Check List</h1>

<%= render 'form' %>

<%= link_to 'Back', check_lists_path %>

app/views/check_lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="check_list_title"><%= @check_list.title %></h2>
<p class="check_list_sub_title"><%= @check_list.description %></p>

<div id="items_wrapper">
  <%= render @check_list.items %>
  <div id="form">
    <%= render "items/form" %>
  </div>
</div>
<div class="links">
  <%= link_to 'Edit', edit_check_list_path(@check_list) %> |
  <%= link_to 'Home', check_lists_path %> |
  <%= link_to 'Delete', check_list_path(@check_list), method: :delete, data: {confirm: "Are you sure?"} %>
</div>

app/views/home/index.html.erb
<div id="center-stage">
  <h1>Checkitoff</h1>
  <h2>A self destructing to-do list that keeps you focused on the things that really matter.</h2>
</div>

app/views/items/_form.html.erb
<%= form_for([@check_list, @check_list.items.build]) do |f| %>
<%= f.text_field :content, placeholder: "New Item" %>
<%= f.submit %>
<% end %>

app/views/items/_item.html.erb
<div clas="row clearfix">
  <!-- <div class="complete"> -->
    <%= link_to complete_check_list_item_path(@check_list, item.id), method: :patch, class: "pull-left checkmark" do %>
      <i style="opacity: 0.4;" class="fa fa-check"></i>
    <% end %>
  <!-- </div> -->
  <!-- <div class="trash"> -->
    <span style="opacity: 0.4;" class=<%= item.completed ? "completed" : ""%> ><%= item.content %></span>
    <%= link_to check_list_item_path(@check_list, item.id), method: :delete, data: {confirm: "Are you sure?"}, class: "pull-right trash" do %>
      <i class="fa fa-trash"></i>
    <% end %>
  <!-- </div> -->
  <!-- <div class="days left"> -->
    <small class="pull-right white inliner days_left"><%= item.days_left %> days left</small>
  <!-- </div> -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Checkitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:900' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
<div class="container"
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<%= yield %>
</div>

</body>
</html>

app/views/users/show.html.erb
<h1 @user </h1>